### ISSUE TITLE
[BUG] KeyError: 'extensions'

### ISSUE THREAD

**Issue by Hedwig7s** [WorldObservationLog/reddit-place-script-2023#6]
```
2023-07-21 23:54:15.245 | WARNING  | __main__:set_pixel_and_check_ratelimit:118 - Thread #7 - Censored: Attempting to place Blue (13) pixel at removed,removed
2023-07-21 23:54:15.695 | SUCCESS  | __main__:set_pixel_and_check_ratelimit:185 - Thread #7 - Censored: Succeeded placing pixel
Exception in thread Thread-7 (task):
Traceback (most recent call last):
  File "C:\Users\Censored\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Censored\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Censored\Downloads\reddit-place-script-2023-main\main.py", line 668, in task
    next_pixel_placement_time = self.set_pixel_and_check_ratelimit(
  File "C:\Users\Censored\Downloads\reddit-place-script-2023-main\main.py", line 172, in set_pixel_and_check_ratelimit
    response.json()["errors"][0]["extensions"]["nextAvailablePixelTs"]
KeyError: 'extensions'
```

**Comment by WorldObservationLog** [comment]
please update to commit 9ba09a3 and seem if it works

**Comment by Hedwig7s** [comment]
Error persists

**Comment by Hedwig7s** [comment]
Error persisted

**Comment by WorldObservationLog** [comment]
> Error persisted

try to update to commit 9ba09a3
