### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NFKRZZ** [WorldObservationLog/reddit-place-script-2023#7]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [~] I have made sure this is not a duplicate issue.
- [ x] I have filled out this form correctly.

## Describe the bug
connection error when trying to login, proxies not working?

## To Reproduce

Steps to trigger the bug:

put in proxies into config.json and run the script
fails to do               552:      client.get("https://www.reddit.com")

## Expected behavior
successful login

**Comment by WorldObservationLog** [comment]
Only https and socks proxy are able to use. I recommend to use tor.

**Comment by NFKRZZ** [comment]
tor does not fix this issue either

**Comment by WorldObservationLog** [comment]
I use builtin tor and it works well. Maybe you should check your Internet connection to make sure that the tor can be directly connnected without other settings

**Comment by NFKRZZ** [comment]
I can use the tor browser perfectly fine

This is a more in depth trace of error

`2023-07-21 15:56:51.767 | INFO     | src.proxy:tor_reconnect:140 - New Tor connection processing
2023-07-21 15:56:52.761 | ERROR    | __main__:task:585 - Failed to connect to websocket, trying again in 30 seconds...
2023-07-21 15:56:52.762 | ERROR    | __main__:task:588 - Traceback (most recent call last):
  File "C:\Users\winga\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "C:\Users\winga\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "C:\Users\winga\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 193, in proxy_manager_for
    manager = self.proxy_manager[proxy] = proxy_from_url(
  File "C:\Users\winga\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 537, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "C:\Users\winga\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 481, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Proxy URL had no scheme, should start with http:// or https://

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\winga\Desktop\reddit-Place\2023\reddit-place-script-2023\main.py", line 551, in task
    client.get("https://www.reddit.com")
  File "C:\Users\winga\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\winga\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\winga\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\winga\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 414, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Proxy URL had no scheme, should start with http:// or https://`

**Comment by WorldObservationLog** [comment]
your proxy address should look like "http://127.0.0.1:7890"
if you want to use tor, please firstly clean up your proxy settings

**Comment by NFKRZZ** [comment]
my apologies my requests api was corrupted
