### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghost** [WorldObservationLog/reddit-place-script-2023#8]
# Bug Report Form

## Checklist

- [X] I am using the latest version of the code.
- [X] I am absolutely sure I read the README in its entirety.
- [X] I have made sure this is not a duplicate issue.
- [X] I have filled out this form correctly.

## Describe the bug

Bug appears to be related to pixel placement, regarding with the keyword `extensions` (like lines 209, 289 and 327).

## To Reproduce

Pretty much run the program as normal.

## Expected behavior

Should just place a pixel.

## Additional context

Performed a `git pull` and `git reset --hard` in an attempt to fix the issue with no dice (in case Git did a funny).

Error log provided - if you need me to verbose it, lemme know.
```
2023-07-22 01:02:05.442 | WARNING  | __main__:set_pixel_and_check_ratelimit:118 - Thread #0 - GeneralElectricTiger: Attempting to place Orange (3) pixel at 1129, 915
2023-07-22 01:02:05.844 | ERROR    | __main__:set_pixel_and_check_ratelimit:172 - GeneralElectricTiger - Access Token is expired, waiting for update...
Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\me\Desktop\r-place bots\reddit-place-script-2023\main.py", line 673, in task
    next_pixel_placement_time = self.set_pixel_and_check_ratelimit(
  File "C:\Users\me\Desktop\r-place bots\reddit-place-script-2023\main.py", line 174, in set_pixel_and_check_ratelimit
    response.json()["errors"][0]["extensions"]["nextAvailablePixelTs"]
KeyError: 'extensions'
```

**Comment by WorldObservationLog** [comment]
plz execute `git rev-parse HEAD` and post the output

**Comment by ghost** [comment]
`5655c00be628326b0e01c86b4da31fb0c41ce774`

> plz execute `git rev-parse HEAD` and post the output

**Comment by WorldObservationLog** [comment]
> `5655c00be628326b0e01c86b4da31fb0c41ce774`
> 
> > plz execute `git rev-parse HEAD` and post the output

It's an old version. plz update to commit 1e93c26
